#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
. ./common.sh

require_docker_image

docker_run bash -s <<'CONTAINER_SCRIPT'
set -euo pipefail

workdir=/tmp/pgopt-pt4-generated-batch
rm -rf "${workdir}"
mkdir -p "${workdir}"
cd "${workdir}"

stage_inputs() {
    # Candidate coordinates are generated by ACNN, but the creation request and
    # SVASP template are stored as fixtures for easy review.
    cp "${PGOPT_TEST_FIXTURES}/unit/fixtures/pt4-generated-batch/pt4-create.json" .
    cp "${PGOPT_TEST_FIXTURES}/unit/fixtures/pt4-generated-batch/svasp.template.in" .
}

generate_candidates() {
acnnmain pt4-create.json > create.out
test -s OUT-pt4-gas/fil_structs.xyz.0
}

extract_candidate() {
    local idx="$1"
    start=$((idx * 6 + 1))
    stop=$((start + 5))
    awk -v start="${start}" -v stop="${stop}" "NR>=start && NR<=stop {print}" \
        OUT-pt4-gas/fil_structs.xyz.0 > "coords-${idx}.xyz"
    test -s "coords-${idx}.xyz"
}

write_svasp_input() {
    local idx="$1"

    sed "s/@IDX@/${idx}/g" svasp.template.in > "svasp-${idx}.in"
}

run_relaxation() {
    local idx="$1"
    SVASP < "svasp-${idx}.in" > "svasp-${idx}.out" 2>&1
    test -s "pt4-batch-${idx}.chk/OUTCAR"
    test -s "pt4-batch-${idx}.chk/CONTCAR"
    tail -8 "svasp-${idx}.out"
}

stage_inputs
generate_candidates
for idx in 0 1 2; do
    extract_candidate "${idx}"
    write_svasp_input "${idx}"
    run_relaxation "${idx}"
done

echo "generated Pt4 batch smoke ok"
CONTAINER_SCRIPT
